# workflow
name: "practice"

# triggers
on:
  push:
    branches: ["main"]
# jobs
jobs:
  deploy-practice:
    # runners
    runs-on: ubuntu-latest
    env:
      NAME: CodigoFacilito
    # steps to run
    steps:
      - run: echo "Hello Github Actions"
      - run: echo "Variable de entorno $NAME"
      # - run: npm i
      # - run: npm run
      # - uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./build

  second-job:
    runs-on: ubuntu-latest
    needs: deploy-practice # if deploy-practice is not run first won't run second job
    steps:
      - run: echo "Hello Second Job Dependency"

  third-job:
    if: ${{github.ref == 'refs/heads/main'}} # github contexts ${{ }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello Third Job"
