# workflow
name: "practice"

# triggers
on:
  push:
    branches: ["main"]
# jobs
jobs:
  deploy-practice:
    # runners
    runs-on: ubuntu-latest
    # steps to run
    steps:
      - run: echo "Hello Github Actions"
      # - run: npm i
      # - run: npm run
      # - uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./build
  second-job:
    runs-on: ubuntu-latest

    steps:
      name: Hola Mundo
      - run: echo "Segundo Job"
