# workflow
name: "practice"

# triggers
on:
  push:
    branches: ["main"]
# jobs
jobs:
  deploy-practice:
    # runners
    runs-on: ubuntu-latest
    outputs:
      exit: ${{ steps. step_1.outputs.variable}}
    env:
      NAME: CodigoFacilito
    # steps to run
    steps:
      - name: Echos al Mundo
        id: step_1
        # Echo of the environment variable
        run: echo "Hello Github Actions $NAME"
      # - run: npm i
      # - run: npm run
      # - uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./build
      - run: echo "variable = Store" >> $GITHUB_OUTPUT #

      - name: Obtener Mensajes
        run: echo "${{ steps. step_1.outputs.variable}}"

  second-job:
    runs-on: ubuntu-latest
    needs: deploy-practice # if deploy-practice is not run first won't run second job
    env:
      EXIT: ${{ needs.deploy-practice.outputs.exit }}
    steps:
      - run: echo "Hello Second Job Dependency $EXIT"

  third-job:
    # github contexts ${{ }}
    if: ${{github.ref == 'refs/heads/main'}}
    runs-on: ubuntu-latest
    steps:
      - name: Working dir
        run: ls -al

      - name: Action
        uses: actions/checkout@v4

      - name: Working dir after Actions
        run: ls -al
  # Artifacts
  fourth-job:
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: |
          echo "Archivo de prueba" >> prueba.log
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: prueba.log
