# workflow
name: "integration"

# triggers
on:
  push:
    branches: ["main"]
# jobs
jobs:
  build:
    # runners
    runs-on: ubuntu-latest
    # services if there's more than one
    # services:
    #   redis:
    #     image: redis
    #     ports:
    #       - 6379:6379
    # steps to run
    steps:
      # - name: Install redis cli
      # # the flag -y is to aprove automatically the command
      #   run: sudo apt-get update -y && sudo apt-get install redis-tools -y
      # - name: Test redis
      #   run: redis-cli -h localhost -p 6379 ping
      - name: Echo 
        run: echo "${{secrets.GITHUB_TOKEN}}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install 
    
    # run the test after installing dependencies
      - name: Run Test
        run: npm run test
  # second job that needs the first one to be completed
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: deploy
        run: echo "Deploy..."  
